### ISSUE TITLE
(URGENT) "Changes" extraction process seems broken

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod-utils#237]
Current version compared to previous:

<img width="554" alt="Screenshot 2024-02-01 at 11 23 24 AM" src="https://github.com/metanorma/stepmod-utils/assets/11865/b61416e4-ec35-4bb1-83ed-a1a52e269578">

Source: `data/modules/wire_and_cable_design_connectivity/module.xml`
```xml
   <changes>
      <change version="2">
         <arm.changes><!-- ... -->
            <arm.modifications>
               <modified.object type="ENTITY" name="Cable_occurrence">
                  <description>
                     <ul>
                        <li>Remove DERIVE 'ends_a'</li>
                        <li>Remove DERIVE 'ends_b'</li>
                        <li>Remove DERIVE 'intermediates'</li>
                        <li>WHERE 'WR1' expression changed</li>
                        <li>WHERE 'WR2' expression changed</li>
                        <li>WHERE 'WR3' expression changed</li>
                     </ul>
                  </description>
               </modified.object>
               <modified.object type="ENTITY" name="Cable_occurrence_terminal_location_group">
                  <description>
						Add WHERE 'WR1'

					</description>
```

@HassanAkbar can you please help fix this ASAP?

**Comment by HassanAkbar** [comment]
```xml
<changes>
  <change version="2">
     <arm.changes><!-- Express Engine 5.0.0 (GIT 04d0208) --><!-- Reference_Schema: WIRE_AND_CABLE_DESIGN_CONNECTIVITY_ARM --><!-- Path: /Users/klt/Projets/STEPmodSMRLv8/stepmod/data/modules/wire_and_cable_design_connectivity/arm.exp --><!-- Trial_schema: WIRE_AND_CABLE_DESIGN_CONNECTIVITY_ARM --><!-- Path: /Users/klt/Projets/cvs.boost-lab.net/stepmod/data/modules/wire_and_cable_design_connectivity/arm.exp -->
        <arm.modifications>
           <modified.object type="ENTITY" name="Cable_occurrence">
              <description>
                 <ul>
                    <li>Remove DERIVE 'ends_a'</li>
                    <li>Remove DERIVE 'ends_b'</li>
                    <li>Remove DERIVE 'intermediates'</li>
                    <li>WHERE 'WR1' expression changed</li>
                    <li>WHERE 'WR2' expression changed</li>
                    <li>WHERE 'WR3' expression changed</li>
                 </ul>
              </description>
           </modified.object>
           <modified.object type="ENTITY" name="Cable_occurrence_terminal_location_group">
              <description>
                    Add WHERE 'WR1'

                </description>
           </modified.object>
           <modified.object type="ENTITY" name="Wire_occurrence">
              <description>
                 <ul>
                    <li>Remove DERIVE 'ends_a'</li>
                    <li>Remove DERIVE 'ends_b'</li>
                    <li>Remove DERIVE 'intermediates'</li>
                    <li>WHERE 'WR1' expression changed</li>
                    <li>WHERE 'WR2' expression changed</li>
                    <li>Add WHERE 'WR6'
                        </li>
                 </ul>
              </description>
           </modified.object>
           <modified.object type="ENTITY" name="Wire_occurrence_terminal">
              <description>
                Add WHERE 'WR1'

              </description>
           </modified.object>
        </arm.modifications>
     </arm.changes>
  </change>
</changes>
```

@ronaldtse I'm currently using `SMRLv9` branch from [iso-10303-stepmod-wg12](https://github.com/metanorma/iso-10303-stepmod-wg12) repo. and I've looked at the file and found no `arm_lf`, `mim` or `mim_lf` changes in it. Only changes that are present are `arm` changes and they are correctly getting populated in the `arm.changes.yml` file as shown below. 

I think the description in `mim_lf.changes.yaml` was actually a bug which was fixed in https://github.com/metanorma/stepmod-utils/issues/235. Am I missing something here?

```yaml
# data/modules/wire_and_cable_design_connectivity/arm.changes.yaml
---
schema: wire_and_cable_design_connectivity
change_edition:
- version: '2'
  modifications:
  - :type: ENTITY
    :name: Cable_occurrence
    :description: |-
      * Remove DERIVE 'ends_a'
      * Remove DERIVE 'ends_b'
      * Remove DERIVE 'intermediates'
      * WHERE 'WR1' expression changed
      * WHERE 'WR2' expression changed
      * WHERE 'WR3' expression changed
  - :type: ENTITY
    :name: Cable_occurrence_terminal_location_group
    :description: Add WHERE 'WR1'
  - :type: ENTITY
    :name: Wire_occurrence
    :description: |-
      * Remove DERIVE 'ends_a'
      * Remove DERIVE 'ends_b'
      * Remove DERIVE 'intermediates'
      * WHERE 'WR1' expression changed
      * WHERE 'WR2' expression changed
      * Add WHERE 'WR6'
  - :type: ENTITY
    :name: Wire_occurrence_terminal
    :description: Add WHERE 'WR1'
```

**Comment by ronaldtse** [comment]
Actually, can you try the “develop” branch?

**Comment by HassanAkbar** [comment]
> Actually, can you try the “develop” branch?

I didn't know that we shifted to develop branch. I will check now.

**Comment by ronaldtse** [comment]
Actually we want to target the develop branch, which provides the most details for now. The SMRLv9 branch is no longer current enough.

**Comment by HassanAkbar** [comment]
@ronaldtse I've tried on the develop branch and still no `arm_lf`, `mim` or `mim_lf` changes in the [xml file](https://github.com/metanorma/iso-10303-stepmod-wg12/blob/develop/data/modules/wire_and_cable_design_connectivity/module.xml#L41). 
The `arm` changes have version 2 and 3 that are getting populated correctly in the `arm.changes.yaml`.

```yaml
---
schema: wire_and_cable_design_connectivity
change_edition:
- version: '2'
  modifications:
  - :type: ENTITY
    :name: Cable_occurrence
    :description: |-
      * Remove DERIVE 'ends_a'
      * Remove DERIVE 'ends_b'
      * Remove DERIVE 'intermediates'
      * WHERE 'WR1' expression changed
      * WHERE 'WR2' expression changed
      * WHERE 'WR3' expression changed
  - :type: ENTITY
    :name: Cable_occurrence_terminal_location_group
    :description: Add WHERE 'WR1'
  - :type: ENTITY
    :name: Wire_occurrence
    :description: |-
      * Remove DERIVE 'ends_a'
      * Remove DERIVE 'ends_b'
      * Remove DERIVE 'intermediates'
      * WHERE 'WR1' expression changed
      * WHERE 'WR2' expression changed
      * Add WHERE 'WR6'
  - :type: ENTITY
    :name: Wire_occurrence_terminal
    :description: Add WHERE 'WR1'
- version: '3'
  additions:
  - :type: ENTITY
    :name: wire_occurrence_identification
  - :type: ENTITY
    :name: wire_part_identification
  modifications:
  - :type: ENTITY
    :name: Cable_occurrence_terminal
    :description: Attribute 'associated_transport_feature' type changed
  - :type: ENTITY
    :name: Wire_occurrence_terminal
    :description: Attribute 'associated_transport_feature' type changed
  deletions:
  - :type: ENTITY
    :name: wire_identification
```

**Comment by ronaldtse** [comment]
@HassanAkbar i believe in the example you have, the description for version 2 is entirely missing.

**Comment by ronaldtse** [comment]
Actually maybe not? I’ll have to back to check. Anyway, are you able to see my content as posted in the OP?

**Comment by HassanAkbar** [comment]
@ronaldtse not sure what do you mean by OP? but the description is present in version 2.

<img width="942" alt="Screenshot 2024-02-01 at 1 42 06 PM" src="https://github.com/metanorma/stepmod-utils/assets/5301572/d0924379-0026-498d-bf4a-f95b56a178c2">

**Comment by HassanAkbar** [comment]
@ronaldtse In OP, I can see that the description got removed.
It was actually a bug that added the incorrect description which was fixed in https://github.com/metanorma/stepmod-utils/issues/235.

**Comment by ronaldtse** [comment]
@HassanAkbar the extraction of changes is STILL incorrect.

There are only 6 files with `<arm_longform.changes>` and 4 files with `<mim_longform.changes>`:

<img width="511" alt="Screenshot 2024-02-06 at 8 57 41 AM" src="https://github.com/metanorma/stepmod-utils/assets/11865/4857ef24-5059-4b67-a04b-9d484878d54b">
<img width="508" alt="Screenshot 2024-02-06 at 8 57 47 AM" src="https://github.com/metanorma/stepmod-utils/assets/11865/f8f57eb5-d0d4-4589-9eee-63e4b8e13728">

This means there should ONLY be 6 `arm_lf.changes.yaml` and 4 `mim_lf.changes.yaml` files.

However, now you have 696 of either files:
```
$ find . -name 'arm_lf.changes.yaml' | wc -l
     696
find . -name 'mim_lf.changes.yaml' | wc -l
     696
```

Please fix this ASAP.

**Comment by HassanAkbar** [comment]
@ronaldtse The issue here is that `arm_lf.changes.yaml` and `mim_lf.changes.yaml` files are being generated for all the schemas but are empty for schemas that do not have these changes.
I have updated the code and now it no longer generates these files if they are empty.

But there are some files that have a changes block as the one below for [activity/module.xml](https://github.com/metanorma/iso-10303-stepmod-wg12/blob/main/data/modules/activity/module.xml#L39). which contains general description not associated to any specific change.

```xml
<changes>
      <change version="2">
         <description> No ARM EXPRESS declarations and interface specifications have been added,
            removed or modified. Definition added for "Activity" and description of the
            "chosen_method" attribute of Activity clarified. </description>
           </change> 
       <change version="3">
        <description>
        Updated bibliography.
        </description>      
       </change>
   </changes>
```

So, for these changes, do we need to generate all 4 files (`arm.changes.yaml`, `mim.changes.yaml`, `arm_lf.changes.yaml`, `mim_lf.changes.yaml`) with same data?

**Comment by ronaldtse** [comment]
@HassanAkbar I just figured out.

In a `module.xml` document:

* `changes/change` are changes of the document
* `changes/mapping.change` are changes to the "mapping spec" which is a particular technical content of the Module document => `mapping.changes.yaml`
* `changes/arm.change` are changes to the ARM => `arm.changes.yaml`
* `changes/mim.change` are changes of the MIM => `mim.changes.yaml`
* `changes/arm_longform.change` are changes to the ARM in Longform => `arm_lf.changes.yaml`
* `changes/mim_longform.change` are changes of the MIM in Longform => `mim_lf.changes.yaml`

The `changes/change` is for the document, perhaps we should have a separate Change YAML `changes.yaml` file for "document changes" at the document level.

**Comment by HassanAkbar** [comment]
@ronaldtse Got it, I'll update the PR according to this.

**Comment by ronaldtse** [comment]
Done in #238 .
